### ISSUE TITLE
Consider using nc instead of nmap

### ISSUE THREAD

**Issue by Ashex** [mrjackyliang/tunnelChecker#2]
nmap is overkill for doing a simple port check, it would make more sense to use ncat instead since all you're doing is checking if a port is accepting TCP/UDP connections. 
I believe the command to use would be `nc -z $VPN_ADDR $PORT_FORWARD` then check the exit code.

**Comment by coolboiime** [comment]
Thanks for the suggestion! Did you get to try the script out using `ncat`? Would love the result of it!

**Comment by Ashex** [comment]
I haven't since I'm using a different method for checking that the vpn tunnel is up. I can submit a PR with the necessary changes so you can test/validate it yourself though.

**Comment by coolboiime** [comment]
Sure, let me know when you submit it!

**Comment by mrjackyliang** [comment]
Check comment on #3.
